export type Hotel = {
  id: string;
  name: string;
  domain: string;
  createdAt: Date;
  logoUrl?: string;
  contactEmail?: string;
  contactPhone?: string;
  address?: string;
  bankDetails?: {
    accountHolder: string;
    iban: string;
    bic: string;
    bankName: string;
  };
  smtp?: {
    host: string;
    port: number;
    user: string;
    pass: string;
  };
  hotelier?: {
    email: string;
  };
  roomCategories?: string[];
  mealTypes?: string[];
};

export type BookingStatus =
  | 'Sent'
  | 'Partial Payment'
  | 'Confirmed'
  | 'Cancelled'
  | 'Draft'
  | 'Completed';

export type Guest = {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  age?: number;
  idFrontUrl?: string;
  idBackUrl?: string;
};

export type Booking = {
  id?: string; // Made optional as it will be auto-generated by Firestore
  hotelId: string;
  guest: Pick<Guest, 'firstName' | 'lastName'>;
  checkIn: Date;
  checkOut: Date;
  status: BookingStatus;
  totalPrice: number;
  lastChanged: Date;
  guestDetails?: Guest;
  room: {
    type: string;
    adults: number;
    children: number;
  };
  mealType: string;
  language: string;
  notes?: string;
  paymentOption?: 'deposit' | 'full';
  paymentProofUrl?: string;
};
