export type Hotel = {
  id: string;
  name: string;
  domain: string;
  createdAt: Date;
  logoUrl?: string;
  contactEmail?: string;
  contactPhone?: string;
  address?: string;
  bankDetails?: {
    accountHolder: string;
    iban: string;
    bic: string;
    bankName: string;
  };
  smtp?: {
    host: string;
    port: number;
    user: string;
    pass: string;
  };
  hotelier?: {
    email: string;
  };
  roomCategories?: string[];
  mealTypes?: string[];
};

export type BookingStatus = 'Sent' | 'Partial Payment' | 'Confirmed' | 'Cancelled';

export type Guest = {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
};

export type Booking = {
  id?: string; // Made optional as it will be auto-generated by Firestore
  guest: Pick<Guest, 'firstName' | 'lastName'>;
  checkIn: Date;
  checkOut: Date;
  status: BookingStatus;
  totalPrice: number;
  lastChanged: Date;
  guestDetails?: Guest;
  room: {
    type: string;
    adults: number;
    children: number;
  };
  mealType: string;
};